name: Check Shell Scripts

on:
  push:
    paths:
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix
      - name: Check all shell scripts for syntax errors
        run: |
          find . -name '*.sh' -exec dos2unix {} +
          find . -name '*.sh' -print0 | xargs -0 -P"$(nproc)" -I{} bash -n "{}"
